# Generated by Django 4.2.6 on 2023-11-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='location',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
