# Generated by Django 4.2.6 on 2023-11-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_date_test_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Admin', 'Admin')], max_length=1000, null=True),
        ),
    ]
